version: "3.9"

services:
  app:
    container_name: toolbox-backend
    build: .
    ports:
      - "4000:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: npm run start
